import type {
  SkyGuideAiProvider,
  SkyGuideAnswer,
  SkyGuideProviderInput,
  SkyGuideSemanticScopeClassifier,
  SkyGuideSemanticScopeDecision,
} from "../skyguide/application/skyGuideAssistant";
import type { SkyGuideContext } from "../skyguide/domain/skyGuide";
import type { SkyGuideToolId } from "../skyguide/application/skyGuideToolRouter";

const AVIATION_SIGNAL =
  /\b(?:aircraft|airplane|flight|airport|aviation|a380|a320|b747|eham|ams|schiphol|metar|taf|weather|runway|vlucht|vliegtuig|luchthaven|weer|flug|flughafen|avion|aéroport|aeropuerto)\b|(?:طائر|مطار|طيران|飛行機|空港)/iu;
const NON_AVIATION_SIGNAL =
  /\b(?:recipe|football|medical|recept|voetbal|medizin|receta|fútbol)\b/iu;

export class LocalSkyGuideProvider
  implements SkyGuideAiProvider, SkyGuideSemanticScopeClassifier
{
  async classifyScope(
    query: string,
    context: SkyGuideContext,
  ): Promise<SkyGuideSemanticScopeDecision> {
    const accepted =
      !NON_AVIATION_SIGNAL.test(query) &&
      (AVIATION_SIGNAL.test(query) || context.selectedAircraft !== null);
    return {
      accepted,
      language: detectLanguage(query),
      refusal: "This local SkyGuide fixture answers aviation questions only.",
      toolPlan: {
        tools: routeFixtureTools(query),
        useWebSearch: false,
      },
    };
  }

  async answer(input: SkyGuideProviderInput): Promise<SkyGuideAnswer> {
    const selected = input.context.selectedAircraft;
    const airportQuestion = /(?:eham|ams|schiphol|airport|luchthaven|空港|مطار)/iu.test(
      input.query,
    );
    const weatherQuestion = /(?:weather|weer|metar|taf|天気|طقس)/iu.test(input.query);
    const subject = selected
      ? `${selected.callsign ?? selected.id} (${selected.id})`
      : airportQuestion
        ? "Amsterdam Airport Schiphol (EHAM/AMS)"
        : "the requested aviation subject";
    return {
      answer: weatherQuestion
        ? "Local test weather: wind 240° at 8 m/s, visibility 10 km, no significant weather."
        : `Local test data is active. Information for ${subject} is deterministic and contains no live provider data.`,
      facts: airportQuestion
        ? ["EHAM is the ICAO code and AMS is the IATA code used by this fixture."]
        : ["This response was generated by the local SkyGuide fixture."],
      likelyExplanation: [
        "The fixture is designed for repeatable UI, tool-routing and error tests.",
      ],
      unknown: ["No current external provider information is available in local test mode."],
      suggestions: ["Show local airport data", "Explain the selected test aircraft"],
      audienceMode: input.audienceMode,
      status: "cached" as const,
      sources: [
        {
          id: "local-test-fixture",
          label: "SkyTracker local deterministic fixtures",
          dataType: weatherQuestion ? ("weather" as const) : ("cached" as const),
          retrievedAt: "2026-07-29T00:00:00.000Z",
        },
      ],
    };
  }
}

function routeFixtureTools(query: string): readonly SkyGuideToolId[] {
  if (/(?:weather|weer|metar|taf|天気|طقس)/iu.test(query)) {
    return ["aviation-weather"];
  }
  if (/(?:airport|luchthaven|eham|ams|schiphol|空港|مطار)/iu.test(query)) {
    return ["airport-data"];
  }
  return [];
}

function detectLanguage(query: string) {
  if (/[\u0600-\u06ff]/u.test(query)) return "ar";
  if (/[\u3040-\u30ff\u4e00-\u9faf]/u.test(query)) return "ja";
  if (/\b(?:komt|welke|vliegtuig|luchthaven|weer)\b/iu.test(query)) return "nl";
  return "en";
}
